# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

a1 = Album.create(cover: "https://upload.wikimedia.org/wikipedia/commons/a/ac/4-44_album_cover.png", title: "4:44", artist: "Jay Z")
Track.create(name: "Kill Jay Z", minutes: 3, album_id: a1.id)
Track.create(name: "The Story of O.J", minutes: 4, album_id: a1.id)
Track.create(name: "Smile", minutes: 5, album_id: a1.id)
Track.create(name: "Caught Their Eyes", minutes: 3, album_id: a1.id)
Track.create(name: "4:44", minutes: 5, album_id: a1.id)
Track.create(name: "Family Fued", minutes: 4, album_id: a1.id)
Track.create(name: "Bam", minutes: 4, album_id: a1.id)
Track.create(name: "Moonlight", minutes: 2, album_id: a1.id)
Track.create(name: "Marcy Me", minutes: 3, album_id: a1.id)
Track.create(name: "Legacy", minutes: 3, album_id: a1.id)

a2 = Album.create(cover: "https://static-assets.codecademy.com/Courses/learn-ruby-on-rails/BassMusic/beyonce.png", title: "Beyonce", artist: "Beyonce")
Track.create(name: "Pretty Hurts", minutes: 5, album_id: a2.id)
Track.create(name: "Haunted", minutes: 7, album_id: a2.id)
Track.create(name: "Drunk in Love", minutes: 6, album_id: a2.id)
Track.create(name: "Blow", minutes: 6, album_id: a2.id)
Track.create(name: "No Angel", minutes: 4, album_id: a2.id)
Track.create(name: "Partition", minutes: 6, album_id: a2.id)
Track.create(name: "Jealous", minutes: 4, album_id: a2.id)
Track.create(name: "Rocket", minutes: 7, album_id: a2.id)
Track.create(name: "Mine", minutes: 7, album_id: a2.id)
Track.create(name: "XO", minutes: 4, album_id: a2.id)
Track.create(name: "Flawless", minutes: 5, album_id: a2.id)
Track.create(name: "Superpower", minutes: 5, album_id: a2.id)
Track.create(name: "Heaven", minutes: 4, album_id: a2.id)
Track.create(name: "Blue", minutes: 5, album_id: a2.id)

a3 = Album.create(cover: "https://static-assets.codecademy.com/Courses/learn-ruby-on-rails/BassMusic/21.png", title: "21", artist: "Adele")
Track.create(name: "Rolling in the Deep", minutes: 4, album_id: a3.id)
Track.create(name: "Rumour Has It", minutes: 4, album_id: a3.id)
Track.create(name: "Turning Tables", minutes: 5, album_id: a3.id)
Track.create(name: "Don't You Remember", minutes: 5, album_id: a3.id)
Track.create(name: "Set Fire to the Rain", minutes: 5, album_id: a3.id)
Track.create(name: "He Won't Go", minutes: 5, album_id: a3.id)
Track.create(name: "Take it All", minutes: 4, album_id: a3.id)
Track.create(name: "I'll be Waiting", minutes: 5, album_id: a3.id)
Track.create(name: "One and Only", minutes: 6, album_id: a3.id)
Track.create(name: "Lovesong", minutes: 6, album_id: a3.id)

a4 = Album.create(cover: "https://lastfm.freetls.fastly.net/i/u/770x0/8bbbc22e83bb40f1c07956ec8e8f578e.jpg#8bbbc22e83bb40f1c07956ec8e8f578e", title: "racine carree", artist: "Stromae")
Track.create(name: "Ta fete", minutes: 3, album_id: a4.id)
Track.create(name: "Papaoutai", minutes: 4, album_id: a4.id)
Track.create(name: "batard", minutes: 3, album_id: a4.id)
Track.create(name: "ave cesaria", minutes: 4, album_id: a4.id)
Track.create(name: "Tous les memes", minutes: 4, album_id: a4.id)
Track.create(name: "Formidable", minutes: 4, album_id: a4.id)
Track.create(name: "moules frites", minutes: 3, album_id: a4.id)
Track.create(name: "carmen", minutes: 3, album_id: a4.id)
Track.create(name: "humain a l'eau", minutes: 4, album_id: a4.id)
Track.create(name: "quand c'est", minutes: 3, album_id: a4.id)
Track.create(name: "sommeil", minutes: 4, album_id: a4.id)
Track.create(name: "merci", minutes: 5, album_id: a4.id)
Track.create(name: "avf", minutes: 5, album_id: a4.id)

a5 = Album.create(cover: "https://upload.wikimedia.org/wikipedia/commons/e/e7/%22AM%22_%28Arctic_Monkeys%29.jpg", title: "AM", artist: "Artic Monkeys")
Track.create(name: "Do I Wanna Know", minutes: 5, album_id: a5.id)
Track.create(name: "R U Mine", minutes: 3, album_id: a5.id)
Track.create(name: "One For The Road", minutes: 3, album_id: a5.id)
Track.create(name: "Arabella", minutes: 3, album_id: a5.id)
Track.create(name: "I Want It All", minutes: 3, album_id: a5.id)
Track.create(name: "No. 1 Party Anthem", minutes: 4, album_id: a5.id)
Track.create(name: "Mad Sounds", minutes: 4, album_id: a5.id)
Track.create(name: "Fireside", minutes: 3, album_id: a5.id)
Track.create(name: "Why'd You Only Call Me When You're High", minutes: 3, album_id: a5.id)
Track.create(name: "Snap Out Of It", minutes: 3, album_id: a5.id)
Track.create(name: "Knee Socks", minutes: 4, album_id: a5.id)
Track.create(name: "I Wanna Be Yours", minutes: 3, album_id: a5.id)

a6 = Album.create(cover: "https://lastfm.freetls.fastly.net/i/u/770x0/99052cb9c4304f33a104995426c52db8.jpg#99052cb9c4304f33a104995426c52db8", title: "El Camino", artist: "The Black Keys")
Track.create(name: "Lonely Boy", minutes: 3, album_id: a6.id)
Track.create(name: "Dead And Gone", minutes: 4, album_id: a6.id)
Track.create(name: "Gold On The Ceiling", minutes: 4, album_id: a6.id)
Track.create(name: "Little Black Submarines", minutes: 4, album_id: a6.id)
Track.create(name: "Money Maker", minutes: 3, album_id: a6.id)
Track.create(name: "Run Right Back", minutes: 3, album_id: a6.id)
Track.create(name: "Sister", minutes: 3, album_id: a6.id)
Track.create(name: "Hell of a Season", minutes: 4, album_id: a6.id)
Track.create(name: "Stop Stop", minutes: 3, album_id: a6.id)
Track.create(name: "Nova Baby", minutes: 3, album_id: a6.id)
Track.create(name: "Mind Eraser", minutes: 3, album_id: a6.id)

a7 = Album.create(cover: "https://lastfm.freetls.fastly.net/i/u/770x0/9f5df98d096f18e393177402081dc255.jpg#9f5df98d096f18e393177402081dc255", title: "The 20/20 Experience", artist: "The Beatles")
Track.create(name: "Come Together", minutes: 4, album_id: a7.id)
Track.create(name: "Something", minutes: 3, album_id: a7.id)
Track.create(name: "Maxwell's Silver Hammer", minutes: 3, album_id: a7.id)
Track.create(name: "Oh! Darling", minutes: 3, album_id: a7.id)
Track.create(name: "Octopus's Garden", minutes: 3, album_id: a7.id)
Track.create(name: "I Want You (She's So Heavy)", minutes: 8, album_id: a7.id)
Track.create(name: "Here Comes The Sun", minutes: 3, album_id: a7.id)
Track.create(name: "Because", minutes: 3, album_id: a7.id)
Track.create(name: "You Never Give Me Your Money", minutes: 4, album_id: a7.id)
Track.create(name: "Sun King", minutes: 2, album_id: a7.id)
Track.create(name: "Mean Mr Mustatd", minutes: 1, album_id: a7.id)
Track.create(name: "Polythene Pam", minutes: 1, album_id: a7.id)
Track.create(name: "She Came In Through The Bathroom Window", minutes: 2, album_id: a7.id)
Track.create(name: "Golden Slumbers", minutes: 2, album_id: a7.id)
Track.create(name: "Carry That Weight", minutes: 2, album_id: a7.id)
Track.create(name: "The End", minutes: 2, album_id: a7.id)
Track.create(name: "Her Majesty", minutes: 0, album_id: a7.id)